### ISSUE TITLE
Strange behavior of Undo/Redo buffer

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#174]
Sometimes Undo and Redo actions does not react and also undone and overwritten strokes appear when doing redo. Not sure if this one or two issues, but both are related to the order of undo/redo queue.

screencast: https://drive.google.com/file/d/0BwvdX1pBENi1WEhUYm1TcTNrbW8/view

version:

```
commit 7ff94652d6b006a344396ae7d7011bd702fd382b
Author: iirelu <totallymyrealemail@hush.ai>
Date:   Sun Jan 18 12:27:28 2015 +0000
```

**Comment by iirelu** [comment]
Eech, yeah, that definitely looks off. I was going to just put it down to slightly wonky fuzzy history matching, but things undoing/redoing out of order is definitely not supposed to happen.

I'm playing around with it a bit, and the way it takes 2 undos to properly undo something is also exceptionally annoying.

I'll look into things and see if I can't narrow down a few problems.

**Comment by loentar** [comment]
Sorry for off-topic question:
It is technically possible to have two variants of undo buffer: time based or stroke based? Then user have to choose variant he like. For me stroke based history is more intuitive and more convenient. I'm always expecting to undo exactly one stroke, not 2.5, or 3 or 5 (if it drawn fast). Sometimes I use eraser to remove half of undone stroke (undone 1.5 stroke of 3), because first stroke was good but 2 and 3 not that good.
Time+Stroke based buffer (like now) is good for painting, but for drawing lineart, for example, it is not that convenient.
Thanks.

**Comment by achadwick** [comment]
@loentar Possibly, but please raise a separate issue for it.

**Comment by achadwick** [comment]
Zero-pressure events can still put pixels on the screen: splatter brushes, for example. There may be classes of input device out there that don't generate button press/release events while still sending motion (x, y, pressure, ...) events too.

I vaguely recall that the brush engine is only supposed to say that a new timeslice should be begun if pixels have been changed. I'll have a look at it.

**Comment by loentar** [comment]
Thanks. I've added the new issue for stroke based history #175

**Comment by achadwick** [comment]
Thanks. They're related, but separate, if you see what I mean...

**Comment by achadwick** [comment]
Should be fixed now. Or at least the problem with accidental commits of blank strokes (a.k.a. having to press undo an indeterminate number of times) seems to be gone.

I've never been able to reproduce anything happening out of order. I'm fairly confident that fixing the thing I found that was subtly but definitely wrong before 5690ea6 should restore proper atomic behaviour.

Please test, and if you see anything apparently out of order happening please make a new issue about it referencing this one. I'd really appreciate a reliable way to reproduce it as well.

**Comment by loentar** [comment]
For me undo/redo seems to be working as expected now. Thank you very much.

**Comment by NickDefo** [comment]
I'm still seeing this issue in the latest Windows build - Did this fix make it into 1.21?  This imgur album shows the described issue: http://imgur.com/a/wtSLt  (I could not attach the gifs due to the file size)

#### Basic system details

MyPaint version: 1.2.1+gitexport.bcf5a28d
Operating system: Windows 10 64 bit

#### Steps to reproduce

1. Start MyPaint
2.  Begin drawing strokes in rapid succession for a few seconds
3.  After several seconds, hit undo shortly after the last stroke you drew.  
4.  Watch the undo/redo arrows in the upper left corner of the screen - You will see the Redo arrow light up and show you that you have something to redo in the Undo/Redo stack, and then it will immediately gray out, as a new undo event is pushed onto the stack for the last few strokes that you drew.
5.  Hit undo: you will restore everything that you had just tried to undo in step 3.  

This problem can be exacerbated if you made strokes between when you hit undo, and when the undo event was pushed onto the stack, as these strokes will leave the undo/redo stack in a broken state.

Note:  Because this is a timing-dependent bug, it may take a few attempts to reproduce the issue.  It all depends on whether or not a slice of pen events were being added to the undo/redo stack before or after you hit undo.

**Comment by achadwick** [comment]
@NickDefo 
Probably a good idea to report it as a new issue. Thanks for the steps.

I'd like to know whether it works with the latest alpha build too. You can get the on the AppVeyor button on the main page, or [here](https://ci.appveyor.com/project/achadwick/mypaint/branch/master) (click the one for your preferred environment, then the Artifacts tab, and grab the installer exe or the standalone zipfile).
