### ISSUE TITLE
crash at startup when locale is not recognized

### ISSUE THREAD

**Issue by gnudles** [mypaint/mypaint#999]
#### Description of the problem
cannot recognize the locale of my system: "en_IL"

#### Basic system details

MyPaint version: 1.2.0-4.1
Operating system: Ubuntu 18.04.2
Desktop environment:  GNOME

#### Steps to reproduce

1. Start MyPaint from shell:

$ mypaint

#### Backtraces or error messages

```
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr'
INFO: lib.i18n: POSIX: LANG='en_IL'
INFO: lib.i18n: POSIX: LANGUAGE='en_IL:en'
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 450, in <module>
    init_gettext(localepath, localepath_brushlib)
  File "/usr/bin/mypaint", line 262, in init_gettext
    logger.debug("getdefaultlocale(): %r", locale.getdefaultlocale())
  File "/usr/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: en_IL
```

**Comment by don570** [comment]
Try the latest  appimage...
https://github.com/mypaint/mypaint/releases/download/v2.0.0-alpha.11/MyPaint---20190331.AppImage

**Comment by gnudles** [comment]
yet happening with latest...

**Comment by gnudles** [comment]
probably bug in python 2.7 itself...

**Comment by jplloyd** [comment]
This _is_ an upstream bug in both 2.7 and 3 
(still present, but hopefully soon fixed by this: https://github.com/python/cpython/pull/14027)

Still seems silly to crash out over this. Wrapping the `getdefaultlocale()` calls in try-except should be enough, and then falling back to en_US as usual.

**Comment by jplloyd** [comment]
I elected to not handle special cases of this, but unrecognized locales only logs a warning to the console now instead of crashing.

Fixed in 9e03af0fb02332d55267780fa110261ce4fe5be8

**Comment by LevProtter** [comment]
Still happens with the latest appImage for en_IL locale.
easily circumvented by setting the $LANG variable to en_UK or US.
I set my systems locale to fix it for myself.

**Comment by jplloyd** [comment]
You are quite right. This will no longer be a problem after v2.1.0, after which Py2 support will be dropped and the appimage will be switched to Py3, but I'll see about fixing it for v2.1.0
